---
#Playbook to provision RHOSP instances to support the deployment of a three-tier application - App1
- name: Create app1 server instance
  os_server:
    cloud: openstack
    name: app1
    image: rhel-guest
    meta: group=apps,deployment_name=dev
    flavor: m1.medium
    security_groups: apps
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: int_network
    userdata: |
      #!/bin/bash
      cp /root/.ssh/mykey.pem /home/cloud-user/.ssh/mykey.pem
      cp /root/.ssh/openstack.pem /home/cloud-user/.ssh/openstack.pem
      cp /root/.ssh/openstack.pub /home/cloud-user/.ssh/openstack.pub
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  register: instanceip


- name: Add floating IP to app1
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: app1
    network: ext_network
    wait: true
    timeout: 180
  register: instancefloatingip

- name: Show "{{ instanceip }}" public IP
  debug: var=instancefloatingip.floating_ip.floating_ip_address

- name: Wait for app1 to be available
  wait_for:
    host: "{{ instancefloatingip.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  delegate_to: "{{ inventory_hostname }}"
